from typing import Protocol
from uuid import UUID

from app.modules.auth.domain.entities import AuthSession


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...

    def verify(self, password: str, password_hash: str) -> bool: ...


class SessionRepository(Protocol):
    def create(self, session: AuthSession) -> None: ...

    def get_by_token_hash(self, token_hash: str) -> AuthSession | None: ...

    def revoke(self, session_id: UUID) -> None: ...

    def revoke_all_for_user(self, user_id: UUID) -> None: ...


class SessionCache(Protocol):
    def get(self, token_hash: str) -> AuthSession | None: ...

    def set(self, session: AuthSession) -> None: ...

    def delete(self, token_hash: str) -> None: ...
